version: '3'
volumes:
  psql-data:

services:
  php-app:
    build: ./app
    image: php-rag
    container_name: php-app
    env_file:
      - ./env
    depends_on:
      - postgres
      - ollama-container
    command: ["./wait-for-postgres.sh", "", "apache2-foreground"]
    ports:
      - 2037:80
    networks:
      app-env:


  postgres:
    hostname: postgres
    image: ankane/pgvector
    restart: always
    env_file:
      - ./env
    volumes:
      - ./script/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      app-env:
      interface:


  pgadmin:
    image: fenglc/pgadmin4
    container_name: pgadmin
    env_file:
      - ./env
    depends_on:
      - postgres
    ports:
      - 5050:5050
    networks:
      interface:

  ollama-container:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    container_name: ollama-container
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - app-env
    entrypoint: ["/usr/bin/bash", "/entrypoint.sh"]

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    volumes:
      - ./ollama/ollama-webui:/app/backend/data
    depends_on:
      - ollama-container
    ports:
      - 8080:8080
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=http://host.docker.internal:7869 #comma separated ollama hosts
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=valiantlynx AI
      - WEBUI_URL=http://localhost:8080
      - WEBUI_SECRET_KEY=t0p-s3cr3t
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - app-env
    
networks:
  app-env:
  interface: