name: CI — PHP Lint & Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql  # add the extensions you need

      - name: Validate composer.json
        working-directory: app/src
        run: composer validate --strict

      - name: Install dependencies
        working-directory: app/src
        run: composer install --no-progress --prefer-dist

      - name: Run tests (PHPUnit)
        working-directory: app/src
        run: composer test